@echo off
echo Cleaning build directory...
rmdir /S /Q build

echo Running PyInstaller...
venv\Scripts\pyinstaller.exe --clean --noconfirm My_Math-Tutor-QT-V2.spec

echo Harvesting files...
heat dir "dist\My_Math-Tutor-QT-V2" -dr INSTALLDIR -cg InternalComponentGroup -gg -g1 -sf -srd -var "var.SourceDir" -out "packaging\msi\HarvestedFiles.wxs"

echo Compiling WiX...
candle -arch x64 -dSourceDir="dist\My_Math-Tutor-QT-V2" "packaging\msi\installer.wxs" "packaging\msi\HarvestedFiles.wxs"

echo Linking MSI...
light -ext WixUIExtension installer.wixobj HarvestedFiles.wixobj -out My_Math-Tutor-QT-V2.msi
